Last login: Mon Apr  1 23:21:38 on ttys000 linmingyao@linmingyaodeMacBook-Pro ~ % /Users/linmingyao/Documents/netdiskproject zsh: permission denied: /Users/linmingyao/Documents/netdiskproject linmingyao@linmingyaodeMacBook-Pro ~ % cd /Users/linmingyao/Documents/netdiskproject linmingyao@linmingyaodeMacBook-Pro netdiskproject % git remote add origin git@github.com:NetDisk9/frontEnd.git linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch -M main linmingyao@linmingyaodeMacBook-Pro netdiskproject % git push -u origin main error: src refspec main does not match any error: failed to push some refs to 'github.com:NetDisk9/frontEnd.git' linmingyao@linmingyaodeMacBook-Pro netdiskproject % git remote origin linmingyao@linmingyaodeMacBook-Pro netdiskproject % git push -u origin master error: src refspec master does not match any error: failed to push some refs to 'github.com:NetDisk9/frontEnd.git' linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch linmingyao@linmingyaodeMacBook-Pro netdiskproject % git checkout -b main
Switched to a new branch 'main'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git checkout -b main

Switched to a new branch 'main'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'github.com:NetDisk9/frontEnd.git'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git checkout -b main
Switched to a new branch 'main'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git remote add origin git@github.com:NetDisk9/frontEnd.git
error: remote origin already exists.
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch -M main
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'github.com:NetDisk9/frontEnd.git'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git log

fatal: your current branch 'main' does not have any commits yet
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git add netdisk
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git commit
Aborting commit due to empty commit message.
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git push -u origin main

error: src refspec main does not match any
error: failed to push some refs to 'github.com:NetDisk9/frontEnd.git'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git log
fatal: your current branch 'main' does not have any commits yet
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch -a
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch -a

linmingyao@linmingyaodeMacBook-Pro netdiskproject % git checkout -b main

Switched to a new branch 'main'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git add netdisk
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git commit
Aborting commit due to empty commit message.
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git status

On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .DS_Store
	new file:   netdisk/.browserslistrc
	new file:   netdisk/.editorconfig
	new file:   netdisk/.eslintrc.js
	new file:   netdisk/.gitignore
	new file:   netdisk/README.md
	new file:   netdisk/babel.config.js
	new file:   netdisk/jsconfig.json
	new file:   netdisk/package-lock.json
	new file:   netdisk/package.json
	new file:   netdisk/public/favicon.ico
	new file:   netdisk/public/index.html
	new file:   netdisk/src/App.vue
	new file:   netdisk/src/api/enroll.js
	new file:   netdisk/src/api/login.js
	new file:   netdisk/src/assets/bgc.png
	new file:   netdisk/src/assets/home.png
	new file:   netdisk/src/assets/logo.png
	new file:   netdisk/src/assets/logo2.png
	new file:   "netdisk/src/assets/\344\270\252\344\272\272\344\270\255\345\277\203.png"
	new file:   "netdisk/src/assets/\346\233\264\346\224\271\345\257\206\347\240\201.png"
	new file:   "netdisk/src/assets/\347\231\273\345\275\225\346\226\271\345\274\217.png"
	new file:   "netdisk/src/assets/\347\231\273\345\275\225\350\256\276\345\244\207.png"
	new file:   "netdisk/src/assets/\347\231\273\351\231\206\350\256\260\345\275\225.png"
	new file:   "netdisk/src/assets/\351\224\201.png"
	new file:   netdisk/src/components/EnterHistory.vue
	new file:   netdisk/src/components/changeCode.vue
	new file:   netdisk/src/components/devices.vue
	new file:   netdisk/src/components/loginMethods.vue
	new file:   netdisk/src/main.js
	new file:   netdisk/src/router/index.js
	new file:   netdisk/src/store/index.js
	new file:   netdisk/src/styles/common.less
	new file:   netdisk/src/utils/request.js
	new file:   netdisk/src/views/HomeView.vue
	new file:   netdisk/src/views/enroll.vue
	new file:   netdisk/src/views/login/account.vue
	new file:   netdisk/src/views/login/email.vue
	new file:   netdisk/src/views/login/home.vue
	new file:   netdisk/vue.config.js

linmingyao@linmingyaodeMacBook-Pro netdiskproject % git remote add origin git@github.com:NetDisk9/frontEnd.git
error: remote origin already exists.
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'github.com:NetDisk9/frontEnd.git'
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git remote -v
origin	git@github.com:NetDisk9/frontEnd.git (fetch)
origin	git@github.com:NetDisk9/frontEnd.git (push)
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git remote show origin

* remote origin
  Fetch URL: git@github.com:NetDisk9/frontEnd.git
  Push  URL: git@github.com:NetDisk9/frontEnd.git
  HEAD branch: (unknown)
linmingyao@linmingyaodeMacBook-Pro netdiskproject %
linmingyao@linmingyaodeMacBook-Pro netdiskproject %
linmingyao@linmingyaodeMacBook-Pro netdiskproject %
linmingyao@linmingyaodeMacBook-Pro netdiskproject %
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git branch
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git log
fatal: your current branch 'main' does not have any commits yet
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git statu
git: 'statu' is not a git command. See 'git --help'.

The most similar commands are
	status
	stage
	stash
linmingyao@linmingyaodeMacBook-Pro netdiskproject % git status
On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .DS_Store
	new file:   netdisk/.browserslistrc
	new file:   netdisk/.editorconfig
	new file:   netdisk/.eslintrc.js
	new file:   netdisk/.gitignore
	new file:   netdisk/README.md
	new file:   netdisk/babel.config.js
	new file:   netdisk/jsconfig.json
	new file:   netdisk/package-lock.json
	new file:   netdisk/package.json
	new file:   netdisk/public/favicon.ico
	new file:   netdisk/public/index.html
	new file:   netdisk/src/App.vue
	new file:   netdisk/src/api/enroll.js
	new file:   netdisk/src/api/login.js
	new file:   netdisk/src/assets/bgc.png
	new file:   netdisk/src/assets/home.png
	new file:   netdisk/src/assets/logo.png
	new file:   netdisk/src/assets/logo2.png
	new file:   "netdisk/src/assets/\344\270\252\344\272\272\344\270\255\345\277\203.png"
	new file:   "netdisk/src/assets/\346\233\264\346\224\271\345\257\206\347\240\201.png"
	new file:   "netdisk/src/assets/\347\231\273\345\275\225\346\226\271\345\274\217.png"
	new file:   "netdisk/src/assets/\347\231\273\345\275\225\350\256\276\345\244\207.png"
	new file:   "netdisk/src/assets/\347\231\273\351\231\206\350\256\260\345\275\225.png"
	new file:   "netdisk/src/assets/\351\224\201.png"
	new file:   netdisk/src/components/EnterHistory.vue
	new file:   netdisk/src/components/changeCode.vue
	new file:   netdisk/src/components/devices.vue
	new file:   netdisk/src/components/loginMethods.vue
	new file:   netdisk/src/main.js
	new file:   netdisk/src/router/index.js
	new file:   netdisk/src/store/index.js
	new file:   netdisk/src/styles/common.less
	new file:   netdisk/src/utils/request.js
	new file:   netdisk/src/views/HomeView.vue
	new file:   netdisk/src/views/enroll.vue
	new file:   netdisk/src/views/login/account.vue
	new file:   netdisk/src/views/login/email.vue
	new file:   netdisk/src/views/login/home.vue
	new file:   netdisk/vue.config.js

linmingyao@linmingyaodeMacBook-Pro netdiskproject % git commit
hint: Waiting for your editor to close the file...